# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Deploy Test
      uses: appleboy/ssh-action@master
      with:
        node-version: 14
        cache: 'yarn'
        - run: yarn install
        - run: yarn build
        - run: mkdir ~/.ssh
        - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
        - run: chmod 400 ~/.ssh/github-action
        - run: echo -e "Host static\n\tUser root\n\tHostname 172.105.134.49\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config